import Foundation

enum Strings {
    static let appName = String(localized: "app_name")
    static let ok = String(localized: "ok")
    static let cancel = String(localized: "cancel")
    static let error = String(localized: "error")
    static let retry = String(localized: "retry")
    static let loading = String(localized: "loading")

    static let onboardingTitle1 = String(localized: "onboarding_title_1")
    static let onboardingSubtitle1 = String(localized: "onboarding_subtitle_1")
    static let onboardingTitle2 = String(localized: "onboarding_title_2")
    static let onboardingSubtitle2 = String(localized: "onboarding_subtitle_2")
    static let onboardingTitle3 = String(localized: "onboarding_title_3")
    static let onboardingSubtitle3 = String(localized: "onboarding_subtitle_3")
    static let skip = String(localized: "skip")
    static let next = String(localized: "next")
    static let getStarted = String(localized: "get_started")

    static let login = String(localized: "login")
    static let register = String(localized: "register")
    static let email = String(localized: "email")
    static let password = String(localized: "password")
    static let confirmPassword = String(localized: "confirm_password")
    static let name = String(localized: "name")
    static let forgotPassword = String(localized: "forgot_password")
    static let dontHaveAccount = String(localized: "dont_have_account")
    static let alreadyHaveAccount = String(localized: "already_have_account")
    static let sendResetLink = String(localized: "send_reset_link")
    static let resetLinkSent = String(localized: "reset_link_sent")

    static let invalidEmail = String(localized: "invalid_email")
    static let passwordTooShort = String(localized: "password_too_short")
    static let passwordsDontMatch = String(localized: "passwords_dont_match")
    static let nameRequired = String(localized: "name_required")

    static let home = String(localized: "home")
    static let explore = String(localized: "explore")
    static let profile = String(localized: "profile")
    static let noItems = String(localized: "no_items")
    static let pullToRefresh = String(localized: "pull_to_refresh")

    static let settings = String(localized: "settings")
    static let notifications = String(localized: "notifications")
    static let theme = String(localized: "theme")
    static let language = String(localized: "language")
    static let about = String(localized: "about")
    static let version = String(localized: "version")
    static let termsOfService = String(localized: "terms_of_service")
    static let privacyPolicy = String(localized: "privacy_policy")
    static let logout = String(localized: "logout")
    static let dark = String(localized: "dark")
    static let light = String(localized: "light")
    static let system = String(localized: "system")

    static let somethingWentWrong = String(localized: "something_went_wrong")
    static let noConnection = String(localized: "no_connection")
    static let emptyHere = String(localized: "empty_here")
    static let comingSoon = String(localized: "coming_soon")
}
